{% set name = "pyobjc-framework-corebluetooth" %}
{% set version = "10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobjc-framework-CoreBluetooth-{{ version }}.tar.gz
  sha256: dddc9020cd2ca008c7037c61026641fff5d91a608b9e3bda51d4ba6afbb04e3c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [linux or win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - pyobjc-core >=9.1
    - pyobjc-framework-cocoa >=9.1
    - python

test:
  imports:
    - CoreBluetooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
