{% set name = "pyobjc-framework-corebluetooth" %}
{% set version = "9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobjc-framework-CoreBluetooth-{{ version }}.tar.gz
  sha256: bcad28f35db0aa33b559cc5b6cc1ac0622d6bdaea367a4f6a849013258840e3f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [linux or win]

requirements:
  host:
    - pip
    - python
  run:
    - pyobjc-core >=8.5
    - pyobjc-framework-cocoa >=8.5
    - python

test:
  imports:
    - CoreBluetooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
