{% set name = "pyobjc-framework-corebluetooth" %}
{% set version = "10.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c0a077bc3a2466271efa382c1e024630bc43cc6f9ab8f3f97431ad08b1ad52bb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [linux or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - pyobjc-core >=10.3.2
    - pyobjc-framework-cocoa >=10.3.2
    - python

test:
  imports:
    - CoreBluetooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
