{% set name = "pyobjc-framework-corebluetooth" %}
{% set version = "10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobjc-framework-CoreBluetooth-{{ version }}.tar.gz
  sha256: fb69d2c61082935b2b12827c1ba4bb22146eb3d251695fa1d58bbd5835260729

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [linux or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - pyobjc-core >=10.1
    - pyobjc-framework-cocoa >=10.1
    - python

test:
  imports:
    - CoreBluetooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
