{% set name = "pyobjc-framework-corebluetooth" %}
{% set version = "12.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/53/f6/424a21392b3290dab0e8a78bddbe4e71754b9f1cf70d0e1584c03d6df987/pyobjc_framework_corebluetooth-{{ version }}.tar.gz
  sha256: 75aa13f5355be549252d3192864bb3b82eb74c1f667d0527c1388117efffd688

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [linux or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - pyobjc-core >=12.2.2
    - pyobjc-framework-cocoa >=12.2.2
    - python

test:
  imports:
    - CoreBluetooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
