{% set name = "pyobjc-framework-corebluetooth" %}
{% set version = "12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 61ae2a56c3dcb8b7307d833e7d913bd7c063d11a1ea931158facceb38aae21d3

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [linux or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - pyobjc-core >=12.0
    - pyobjc-framework-cocoa >=12.0
    - python

test:
  imports:
    - CoreBluetooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
