schema_version: 1

context:
  version: "12.2.1"

package:
  name: pyobjc-framework-corebluetooth
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyobjc-framework-corebluetooth/pyobjc_framework_corebluetooth-${{ version }}.tar.gz
  sha256: 7dbb285295097205bebbcb11f55161e5faa02111108fb7b17536176e31971eb0

build:
  number: 0
  skip: linux or win
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - pyobjc-core >=12.2
    - pyobjc-framework-cocoa >=12.2
    - python

tests:
  - python:
      imports:
        - CoreBluetooth
      pip_check: true

about:
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt
  homepage: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
