schema_version: 1

context:
  version: "12.2"

package:
  name: pyobjc-framework-corebluetooth
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/52/df/bee7ba216f9fb513710aac1701b78c97b087b37fca8ec1806f8572e0bbb3/pyobjc_framework_corebluetooth-${{ version }}.tar.gz
  sha256: 8b4e5ca99953c360c391a695b0782a5328fcecafd56fdf790ad709e932feb306

build:
  number: 0
  skip: linux or win
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - pyobjc-core >=12.2
    - pyobjc-framework-cocoa >=12.2
    - python

tests:
  - python:
      imports:
        - CoreBluetooth
      pip_check: true

about:
  summary: Wrappers for the framework CoreBluetooth on macOS
  license: MIT
  license_file:
    - LICENSE.txt
  homepage: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
